version: '2'
services:
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: telegraf:1.3.1
    environment:
      HOSTNAME: "telegraf-1"
    # Telegraf requires network access to InfluxDB
    links: 
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:1.2.4
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "38086:8086"
      - "38083:8083"
    environment:
      - ADMIN_USER: "telegraf"
      - INFLUXDB_INIT_PWD: "NATQQ$$!A"
      - PRE_CREATE_DB: "telegraf"